version: '3.8'

services:
  elasticdb:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    container_name: elasticdb
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.0
    container_name: kibana
    depends_on:
      - elasticdb
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticdb:9200
    ports:
      - "5601:5601"

volumes:
  esdata: